on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
